config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :sub_categories
  resources :phase_sectors
  resources :blocks do
    collection do
      get :show_phases
      get :show_blocks
    end
  end

  resources :categories
  resources :items do
    collection do
      get :show_sub_category
      get :show_sub_category_product
      get :show_cities
      get :show_societies
      get :like_dislike
      get :like_dislike_index
      post :update_profile
      post :update_password
    end
  end
  resources :profiles
  resources :home do
    collection do
      get :show_content
      get :autocomplete_json
      get :autocomplete_json1
      get :autocomplete_society
      get :item_active_inactive
      get :user_items
      post :contact_us
      post :update_profile1
    end
  end

  resources :property do
    collection do
      get :autocomplete_society
    end
  end

  resources :search do
    collection do
      # get :
      get :search_property
      post :search
    end
  end


  devise_for :users , :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
      :registrations => "users/registrations",
      :sessions => "users/sessions",
      :passwords => "users/passwords"
  }

  #devise_for :users
  # as :user do

  #get 'admin' => 'users/sessions#new', :as => :new_user_session
  #post 'admin' => 'users/sessions#create', :as => :user_session
  #get "subscriber", :to => "users/sessions#new"
  # get "sign_up", :to => "users/registrations#new"
  #get "sign_out", :to => "users/sessions#destroy"
  # end


  devise_scope :user do
    get 'login', :to => 'users/sessions#new'
    get '/register', :to => "users/registrations#new"
    get "logout", :to => "users/sessions#destroy"
  end

    get "/all-categories/:slug" => "home#all_categories"

  get '/agent/profile',:to => "property#profile_detail"
  get '/faq',:to => "home#faq"
  get '/contact-us',:to => "home#contact"
  get '/account-setting',:to => "items#account_setting"
  get '/change-password',:to => "items#change_password"
  get '/sitemap',:to => "home#sitemap"
  get '/admin',:to => "home#admin"
  get '/about-us',:to => "home#about"
  get '/privacy-policy',:to => "home#privacy"
  get '/terms-conditions',:to => "home#terms"

  # constraints(subdomain: 'zameen') do
    # get '/', to: 'home#index'
  # if request.url.include? "property-sale"
    get '/property-sale', to: 'property#property_for_sale' ,:via => :get
    get '/property-rent', to: 'property#property_for_rent' ,:via => :get

   # ["lahore","gujranwala","gwadar","peshawar","bahawalpur","karachi","faisalabad","islamabad-capital"].each do |list|
     get "property-sale/:slug" => "property#list_city_property_sale"
     get "property-rent/:slug" => "property#list_city_property_rent"
   # end

     get "/:slug" => "search#index"

     get "/property/:slug" => "items#show"

     get "property-sale/:slug1/:slug" => "property#list_city_society_property_sale"
     get "property-rent/:slug1/:slug" => "property#list_city_society_property_rent"
   # end

  # match '/' => 'items#show', :constraints => { :subdomain => /.+/ }


  root :to => "home#index"

  # if Rails.env.production?
  #    get '404', to: 'application#page_not_found'
  #    get '422', to: 'application#server_error'
  #    get '500', to: 'application#server_error'
  # end

  # get '/404', to: 'errors#not_found'
  # get '/500', to: 'errors#internal_server_error'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th> name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>

        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.name %>
</p>



<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>