config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :sub_categories
  resources :phase_sectors
  resources :blocks do
    collection do
      get :show_phases
      get :show_blocks
    end
  end

  resources :categories
  resources :items do
    collection do
      get :show_sub_category
      get :show_sub_category_product
      get :show_cities
      get :show_societies
      get :like_dislike
      get :like_dislike_index
      post :update_profile
      post :update_password
    end
  end
  resources :profiles
  resources :home do
    collection do
      get :show_content
      get :autocomplete_json
      get :autocomplete_json1
      get :autocomplete_society
      get :item_active_inactive
      get :user_items
      post :contact_us
      post :update_profile1
    end
  end

  resources :property do
    collection do
      get :autocomplete_society
    end
  end

  resources :search do
    collection do
      # get :
      get :search_property
      post :search
    end
  end


  devise_for :users , :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
      :registrations => "users/registrations",
      :sessions => "users/sessions",
      :passwords => "users/passwords"
  }

  #devise_for :users
  # as :user do

  #get 'admin' => 'users/sessions#new', :as => :new_user_session
  #post 'admin' => 'users/sessions#create', :as => :user_session
  #get "subscriber", :to => "users/sessions#new"
  # get "sign_up", :to => "users/registrations#new"
  #get "sign_out", :to => "users/sessions#destroy"
  # end


  devise_scope :user do
    get 'login', :to => 'users/sessions#new'
    get '/register', :to => "users/registrations#new"
    get "logout", :to => "users/sessions#destroy"
  end

    get "/all-categories/:slug" => "home#all_categories"

  get '/agent/profile',:to => "property#profile_detail"
  get '/faq',:to => "home#faq"
  get '/contact-us',:to => "home#contact"
  get '/account-setting',:to => "items#account_setting"
  get '/change-password',:to => "items#change_password"
  get '/sitemap',:to => "home#sitemap"
  get '/admin',:to => "home#admin"
  get '/about-us',:to => "home#about"
  get '/privacy-policy',:to => "home#privacy"
  get '/terms-conditions',:to => "home#terms"

  # constraints(subdomain: 'zameen') do
    # get '/', to: 'home#index'
  # if request.url.include? "property-sale"
    get '/property-sale', to: 'property#property_for_sale' ,:via => :get
    get '/property-rent', to: 'property#property_for_rent' ,:via => :get

   # ["lahore","gujranwala","gwadar","peshawar","bahawalpur","karachi","faisalabad","islamabad-capital"].each do |list|
     get "property-sale/:slug" => "property#list_city_property_sale"
     get "property-rent/:slug" => "property#list_city_property_rent"
   # end

     get "/:slug" => "search#index"

     get "/property/:slug" => "items#show"

     get "property-sale/:slug1/:slug" => "property#list_city_society_property_sale"
     get "property-rent/:slug1/:slug" => "property#list_city_society_property_rent"
   # end

  # match '/' => 'items#show', :constraints => { :subdomain => /.+/ }


  root :to => "home#index"

  # if Rails.env.production?
  #    get '404', to: 'application#page_not_found'
  #    get '422', to: 'application#server_error'
  #    get '500', to: 'application#server_error'
  # end

  # get '/404', to: 'errors#not_found'
  # get '/500', to: 'errors#internal_server_error'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phase_sector.rb
class PhaseSector < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged, slug_column: :phase_slug
  belongs_to :society
  belongs_to :city
  has_many :blocks
  validates_uniqueness_of :name



end

app/controllers/phase_sectors_controller.rb
class PhaseSectorsController < ApplicationController

  #TODO currently only give option of add phase sectors. no option for edit

  load_and_authorize_resource
  before_action :set_phase_sector, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    
    @phase_sectors = PhaseSector.all
    # @phase_sectors = PhaseSector.where("category_id = ? or category_id=?",13,14)
    # @bred_crumbs = "/sub_categories"
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
    # @bred_crumbs = "/sub_categories/#{@phase_sector.slug}"
  end

  def show_societies
        @city = City.find_by_id(params[:city_id])
        @societies = @city.societies unless @city.blank?
        render :partial => 'items/societies', :layout => false
    end

  # GET /sub_categories/new
  def new
    @phase_sector = PhaseSector.new
    @cities = City.all
    # @societies = Society.all
    # @bred_crumbs = "/sub_categories/new"
  end

  # GET /sub_categories/1/edit
  def edit
    @cities = City.all
    # @bred_crumbs = "/sub_categories/#{@phase_sector.slug}/edit"
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @phase_sector = PhaseSector.new(phase_sector_params)
    #binding.pry
    # pppppppp
    @phase_sector.society_id = params[:phase_sector][:society_id]
    @phase_sector.city_id = params[:phase_sector][:city_id]
    respond_to do |format|
      if @phase_sector.save
        format.html { redirect_to phase_sectors_path, notice: 'phase sector was successfully created.' }
        format.json { render :show, status: :created, location: @phase_sector }
      else
        @cities = City.all
        flash[:error] = []
        @phase_sector.errors.full_messages.each { |error| flash[:error] << error }
        format.html { render :new }
        format.json { render json: @phase_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @phase_sector.update(phase_sector_params)
        format.html { redirect_to phase_sectors_path, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @phase_sector }
      else
        # @categories = Category.all
        flash[:error] = []
        @phase_sector.errors.full_messages.each { |error| flash[:error] << error }
        format.html { render :edit }
        format.json { render json: @phase_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @phase_sector.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phase_sector
      @phase_sector = PhaseSector.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phase_sector_params
      params.require(:phase_sector).permit(:name, :society_id,:city_id)
    end
end

app/views/phase_sectors/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  </div>
  <div class="panel-body">
    <%= form_with(model: @phase_sector, local: true, :id => "F",:class=>"form-horizontal") do |form| %>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="firstname1">Name</label>

      <div class="col-sm-5">
        <%= form.text_field :name, :class => "form-control", :id => "name", :placeholder => "name" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label" for="firstname1">City</label>

      <div class="col-sm-5">

        <select id="city-p" name="phase_sector[city_id]" class="selectpicker form-control" data-show-subtext="true" data-live-search="true">
          <option value="">Choose a city</option>
          <% @cities.each do |c| %>


              <% if @phase_sector.city == c %>
                  <option value="<%= c.id %>" selected="selected"><%= c.name %></option>
              <% else %>
                  <option value="<%= c.id %>"><%= c.name %> </option>
              <% end %>




          <% end unless @cities.blank? %>
        </select>
      </div>

      <!--</div>-->
    </div>

    <div class="form-group">
      <div class="col-xs-3" id="spin-city" style="display: none"><%= image_tag("/assets/select2-spinner.gif") %></div>
    </div>

    <div class="form-group" id="societies" style="display: none;">
      <%= render 'societies' %>
    </div>


    <div class="form-group">
      <div class="col-sm-9 col-sm-offset-4">
        <!--<button type="submit" class="btn btn-primary" name="signup1" value="Sign up">Sign up</button>-->
        <%= form.submit :class => 'btn btn-info' %>
      </div>
    </div>
    <% end %>
  </div>
</div>




<script type="text/javascript">


    $("#F").validate({
        rules: {
            "phase_sector[name]": {
                required: true,
                minlength: 3
            },
            "phase_sector[city_id]": "required",
            "phase_sector[society_id]": "required"
        },

        messages: {
            "phase_sector[name]": {
                required: "Please enter a phase sector name",
                minlength: "Your sub category name must consist of at least 3 characters"
            },

            "phase_sector[city_id]": "Please choose an option!",
            "phase_sector[society_id]": "Please choose an option!"
        },
        errorElement: "em",
        errorPlacement: function (error, element) {
            // Add the `help-block` class to the error element
            error.addClass("help-block");

            // Add `has-feedback` class to the parent div.form-group
            // in order to add icons to inputs
            element.parents(".col-sm-5").addClass("has-feedback");

            if (element.prop("type") === "checkbox") {
                error.insertAfter(element.parent("label"));
            } else {
                error.insertAfter(element);
            }

            // Add the span element, if doesn't exists, and apply the icon classes to it.
            if (!element.next("span")[0]) {
                $("<span class='glyphicon glyphicon-remove form-control-feedback'></span>").insertAfter(element);
            }
        },
        success: function (label, element) {
            // Add the span element, if doesn't exists, and apply the icon classes to it.
            if (!$(element).next("span")[0]) {
                $("<span class='glyphicon glyphicon-ok form-control-feedback'></span>").insertAfter($(element));
            }
        },
        highlight: function (element, errorClass, validClass) {
            $(element).parents(".col-sm-5").addClass("has-error").removeClass("has-success");
            $(element).next("span").addClass("glyphicon-remove").removeClass("glyphicon-ok");
        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).parents(".col-sm-5").addClass("has-success").removeClass("has-error");
            $(element).next("span").addClass("glyphicon-ok").removeClass("glyphicon-remove");
        }
    });


    $("#city-p").on("change", function () {
        $("#spin-city").css("display", "block");
        var s = $("#societies");
        "" == this.value ? ($("#societies").css("display", "none"), $("#spin-city").css("display", "none")) : $.ajax({
            url: "/items/show_societies?city_id=" + this.value + "&phase=" + $("#category").val(),
            type: "get",
            dataType: "html",
            processData: !1,
            success: function (e) {
                $("#spin-city").css("display", "none"), document.getElementById("societies").style.display = "block", s.html(e)
            }
        })
    });

    $(function () {
        $('select').selectpicker();
    });


</script>

app/views/phase_sectors/_societies.html.erb
<label class="col-sm-4 control-label" for="firstname1">Society</label>

          <div class="col-sm-5">
<select id="Society" name="phase_sector[society_id]" class="selectpicker form-control" data-show-subtext="true" data-live-search="true">
              <option value="">Choose a Society</option>
              <% @societies.each do |c| %>
                  <option value="<%= c.id %>"><%= c.name %> --- <%= c.city.name %> </option>
              <% end unless @societies.blank? %>
            </select>
          </div>


<script>


    $("#Society").on("change", function () {
        $("#spin-city").css("display", "block");
        var s = $("#phases");
        "" == this.value ? ($("#phases").css("display", "none"), $("#spin-city").css("display", "none")) : $.ajax({
            url: "/blocks/show_phases?society_id=" + this.value ,
            type: "get",
            dataType: "html",
            processData: !1,
            success: function (e) {
                $("#spin-city").css("display", "none"), document.getElementById("phases").style.display = "block", s.html(e)
            }
        })


    });

        $('select').selectpicker();
</script>

app/views/phase_sectors/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category ,:class => 'btn btn-info' %>  |
<%= link_to 'Back', sub_categories_path ,:class => 'btn btn-info' %>

app/views/phase_sectors/index.html.erb
<h1 style="text-align: center">Sub Categories</h1>

<table style="margin-left: 10px">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Society</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phase_sectors.each do |phase_sector| %>
      <tr>
        <td><%= phase_sector.id %><%= '-----' %></td>
        <td><%= phase_sector.name %><%="-----------"%></td>
        <td><%= phase_sector.society.name %><%= "          " %></td>
        <td><%= link_to 'Show', phase_sector %></td>
        <td><%#= link_to 'Edit', edit_phase_sector_path(phase_sector) %></td>
        <td><%#= link_to 'Destroy', phase_sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add phase sector', new_phase_sector_path ,:class => 'btn btn-info' %>

app/views/phase_sectors/new.html.erb
<h3>New phase_sector </h3>

<%= render 'form', phase_sector: @phase_sector %>

<%= link_to 'Back', sub_categories_path ,:class => 'btn btn-info' %>

app/views/phase_sectors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @phase_sector.name %>
</p>

<p>
  <strong>Society:</strong>
  <%= @phase_sector.society.name %>
</p>

<%#= link_to 'Edit', edit_phase_sector_path(@phase_sector) ,:class => 'btn btn-info' %>|
<%= link_to 'Back', phase_sectors_path ,:class => 'btn btn-info' %>