config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :sub_categories
  resources :phase_sectors
  resources :blocks do
    collection do
      get :show_phases
      get :show_blocks
    end
  end

  resources :categories
  resources :items do
    collection do
      get :show_sub_category
      get :show_sub_category_product
      get :show_cities
      get :show_societies
      get :like_dislike
      get :like_dislike_index
      post :update_profile
      post :update_password
    end
  end
  resources :profiles
  resources :home do
    collection do
      get :show_content
      get :autocomplete_json
      get :autocomplete_json1
      get :autocomplete_society
      get :item_active_inactive
      get :user_items
      post :contact_us
      post :update_profile1
    end
  end

  resources :property do
    collection do
      get :autocomplete_society
    end
  end

  resources :search do
    collection do
      # get :
      get :search_property
      post :search
    end
  end


  devise_for :users , :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
      :registrations => "users/registrations",
      :sessions => "users/sessions",
      :passwords => "users/passwords"
  }

  #devise_for :users
  # as :user do

  #get 'admin' => 'users/sessions#new', :as => :new_user_session
  #post 'admin' => 'users/sessions#create', :as => :user_session
  #get "subscriber", :to => "users/sessions#new"
  # get "sign_up", :to => "users/registrations#new"
  #get "sign_out", :to => "users/sessions#destroy"
  # end


  devise_scope :user do
    get 'login', :to => 'users/sessions#new'
    get '/register', :to => "users/registrations#new"
    get "logout", :to => "users/sessions#destroy"
  end

    get "/all-categories/:slug" => "home#all_categories"

  get '/agent/profile',:to => "property#profile_detail"
  get '/faq',:to => "home#faq"
  get '/contact-us',:to => "home#contact"
  get '/account-setting',:to => "items#account_setting"
  get '/change-password',:to => "items#change_password"
  get '/sitemap',:to => "home#sitemap"
  get '/admin',:to => "home#admin"
  get '/about-us',:to => "home#about"
  get '/privacy-policy',:to => "home#privacy"
  get '/terms-conditions',:to => "home#terms"

  # constraints(subdomain: 'zameen') do
    # get '/', to: 'home#index'
  # if request.url.include? "property-sale"
    get '/property-sale', to: 'property#property_for_sale' ,:via => :get
    get '/property-rent', to: 'property#property_for_rent' ,:via => :get

   # ["lahore","gujranwala","gwadar","peshawar","bahawalpur","karachi","faisalabad","islamabad-capital"].each do |list|
     get "property-sale/:slug" => "property#list_city_property_sale"
     get "property-rent/:slug" => "property#list_city_property_rent"
   # end

     get "/:slug" => "search#index"

     get "/property/:slug" => "items#show"

     get "property-sale/:slug1/:slug" => "property#list_city_society_property_sale"
     get "property-rent/:slug1/:slug" => "property#list_city_society_property_rent"
   # end

  # match '/' => 'items#show', :constraints => { :subdomain => /.+/ }


  root :to => "home#index"

  # if Rails.env.production?
  #    get '404', to: 'application#page_not_found'
  #    get '422', to: 'application#server_error'
  #    get '500', to: 'application#server_error'
  # end

  # get '/404', to: 'errors#not_found'
  # get '/500', to: 'errors#internal_server_error'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  default_scope {order("name ASC")}
  belongs_to :category
  has_many :products
  has_many :items
  validates_uniqueness_of :name


  def category_and_sub_category_name
    "#{self.category.name}  ----   #{name}"
  end



end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    # @sub_categories = SubCategory.all
    @sub_categories = SubCategory.where("category_id = ? or category_id=?",13,14)
    # @bred_crumbs = "/sub_categories"
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
    # @bred_crumbs = "/sub_categories/#{@sub_category.slug}"
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
    # @categories = Category.all
    # @bred_crumbs = "/sub_categories/new"
  end

  # GET /sub_categories/1/edit
  def edit
    # @categories = Category.all
    # @bred_crumbs = "/sub_categories/#{@sub_category.slug}/edit"
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)
    #binding.pry
    #pppppppp
    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to sub_categories_path, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        # @categories = Category.all
        flash[:error] = []
        @sub_category.errors.full_messages.each { |error| flash[:error] << error }
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        # @categories = Category.all
        flash[:error] = []
        @sub_category.errors.full_messages.each { |error| flash[:error] << error }
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <!--<h3 class="panel-title">Using feedback icons</h3>-->
  </div>
  <div class="panel-body">
    <!--<form id="signupForm1" method="post" class="form-horizontal" action="">-->
    <%= form_with(model: sub_category, local: true, :id => "Form",:class=>"form-horizontal") do |form| %>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="firstname1">Name</label>

      <div class="col-sm-5">
        <!--<input type="text" class="form-control" id="firstname1" name="firstname1" placeholder="First name" />-->
        <%= form.text_field :name, :class => "form-control", :id => "name",  :placeholder => "name" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label" for="firstname1">Category</label>

      <div class="col-sm-5">
        <!--<input type="text" class="form-control" id="firstname1" name="firstname1" placeholder="First name" />-->
        <%#= form.text_field :name, :class => "form-control", :id => "firstname1", :name => "firstname1", :placeholder => "name" %>
        <%#= form.collection_select(:category_id, @categories, :id, :name ,:class => "required",:prompt => "Choose") %>
        <!--<br/>-->
        <select id="select" class="required form-control" name="sub_category[category_id]">
          <option value="">Choose an option</option>
          <% @categories.each do |cat| %>
              <% if @sub_category.category == cat %>
                  <option value="<%= cat.id %>" selected="selected"><%= cat.name %></option>
              <% else %>
                  <option value="<%= cat.id %>"><%= cat.name %></option>
              <% end %>
          <% end  unless @categories.blank? %>
        </select>

      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-9 col-sm-offset-4">
        <!--<button type="submit" class="btn btn-primary" name="signup1" value="Sign up">Sign up</button>-->
        <%= form.submit :class => 'btn btn-info' %>
      </div>
    </div>
    <% end %>
  </div>
</div>




<script>

$("#Form").validate({
     rules:{
         "sub_category[name]":{
             required:true,
             minlength:3
         },
         "sub_category[category_id]": "required"
     },

     messages:{
         "sub_category[name]": {
         						required: "Please enter a sub category name",
         						minlength: "Your sub category name must consist of at least 3 characters"
         					},

         "sub_category[category_id]": "Please choose an option!"
     },
     errorElement:"em",
     errorPlacement:function (error, element) {
         // Add the `help-block` class to the error element
         error.addClass("help-block");

         // Add `has-feedback` class to the parent div.form-group
         // in order to add icons to inputs
         element.parents(".col-sm-5").addClass("has-feedback");

         if (element.prop("type") === "checkbox") {
             error.insertAfter(element.parent("label"));
         } else {
             error.insertAfter(element);
         }

         // Add the span element, if doesn't exists, and apply the icon classes to it.
         if (!element.next("span")[ 0 ]) {
             $("<span class='glyphicon glyphicon-remove form-control-feedback'></span>").insertAfter(element);
         }
     },
     success:function (label, element) {
         // Add the span element, if doesn't exists, and apply the icon classes to it.
         if (!$(element).next("span")[ 0 ]) {
             $("<span class='glyphicon glyphicon-ok form-control-feedback'></span>").insertAfter($(element));
         }
     },
     highlight:function (element, errorClass, validClass) {
         $(element).parents(".col-sm-5").addClass("has-error").removeClass("has-success");
         $(element).next("span").addClass("glyphicon-remove").removeClass("glyphicon-ok");
     },
     unhighlight:function (element, errorClass, validClass) {
         $(element).parents(".col-sm-5").addClass("has-success").removeClass("has-error");
         $(element).next("span").addClass("glyphicon-ok").removeClass("glyphicon-remove");
     }
 });







</script>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category ,:class => 'btn btn-info' %>  |
<%= link_to 'Back', sub_categories_path ,:class => 'btn btn-info' %>

app/views/sub_categories/index.html.erb
<h1 style="text-align: center">Sub Categories</h1>

<table style="margin-left: 10px">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.id %></td>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.category.name %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Category', new_sub_category_path ,:class => 'btn btn-info' %>

app/views/sub_categories/new.html.erb
<h3>New Sub Category</h3>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Back', sub_categories_path ,:class => 'btn btn-info' %>

app/views/sub_categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @sub_category.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @sub_category.category.name %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) ,:class => 'btn btn-info' %>|
<%= link_to 'Back', sub_categories_path ,:class => 'btn btn-info' %>